[ERROR] 2021-04-02 14:26:37,003 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2021-04-02 14:26:36.979603-10.0.2.2-156
